%% Post-Processing
StartPostProcessingTime = tic;

%% Set-up the evaluation points
SetUp_EvaluationPoints

%% Compute the velocity field inside the vessel
VelocityInsideDomain = PostProcessing(EvaluationPts, coord, connect, ...
                                      inletelem, elemDofNum, ...
                                      DirichletElem, NeumannElem, ...
                                      FieldPts, NormalV, Weights, BasisFn, ...
                                      unodal, Telem, ...
                                      grx, grw, gtx, gtw, mu, numGaussPoints, ...
                                      numDofPerNode, numDofPerElem);
PostProcessingTime = toc(StartPostProcessingTime)

%% Plot Settings 
PlotSettings