function x = SolveBEM_GMRES(coord, connect, inletelem, outletelem, ...
                            elemDofNum, ...
                            NeumannDofs, NeumannNode, DirichletElem, ...
                            FieldPts, NormalV, Weights, BasisFn, ...
                            Telem, ...
                            grx, grw, gtx, gtw, mu, numGaussPoints, ...
                            numNodes, numDofPerNode, numDofPerElem, ...
                            ToleranceGMRES)
[A, b, Minv] = ...
             PrecomputeBEM_Vessel(coord, connect, inletelem, outletelem, ...
                                  elemDofNum, ...
                                  NeumannDofs, NeumannNode, DirichletElem, ...
                                  FieldPts, NormalV, Weights, BasisFn, ...
                                  Telem, ...
                                  grx, grw, gtx, gtw, mu, numGaussPoints, ...
                                  numNodes, numDofPerNode, numDofPerElem);

x = gmres(A,b,[],ToleranceGMRES,size(A,1),@PreCondition);

%%
function y = PreCondition(r)
    y = Minv*r;
end
end