function [Speed, MinSpeed, MaxSpeed] = ...
                       ComputeSpeedAtEvaluationPts(EvaluationPts, Velocity)
%%
Speed = reshape(sqrt(Velocity(1,:).^2 + ...
                     Velocity(2,:).^2 + ...
                     Velocity(3,:).^2), ...
                     size(EvaluationPts,1),size(EvaluationPts,2));
MinSpeed = min(min(Speed));
MaxSpeed = max(max(Speed));