function [LineSpeed, CrossSectionSpeedmid, CrossSectionSpeedinlet, ...
          CrossSectionSpeedoutlet, MinCaxis, MaxCaxis] = ...
          SpeedComputations(LinePts, LinePtsX, ...
                            CirclePtsmid, CirclePtsXmid, ...
                            CirclePtsinlet, CirclePtsXinlet, ...
                            CirclePtsoutlet, CirclePtsXoutlet, ...
                            VelocityInsideDomain)
%% Speed computation on the points along the tube length
numelLinePts = numel(LinePtsX);
[LineSpeed, MinLineSpeed, MaxLineSpeed] = ...
       ComputeSpeedAtEvaluationPts(LinePts(:,:,1), ...
                                   VelocityInsideDomain(:,1:numelLinePts));

%% Speed computation of middle cross-section of vessel
numelCirclePtsmid = numel(CirclePtsXmid);
numelLinePtsCirclePtsmid = numelLinePts+numelCirclePtsmid;
rangeInd = numelLinePts+1 : numelLinePtsCirclePtsmid;
[CrossSectionSpeedmid, ...
 MinCrossSectionSpeedmid, MaxCrossSectionSpeedmid] = ...
             ComputeSpeedAtEvaluationPts(CirclePtsmid(:,:,1), ...
                                         VelocityInsideDomain(:,rangeInd));
                               
%% Speed computation of inlet cross-section of vessel
numelCirclePtsinlet = numel(CirclePtsXinlet);
numelLinePtsCirclePtsmid_inlet = numelLinePtsCirclePtsmid + ...
                                 numelCirclePtsinlet;
rangeInd = numelLinePtsCirclePtsmid+1 : numelLinePtsCirclePtsmid_inlet;
[CrossSectionSpeedinlet, ...
 MinCrossSectionSpeedinlet, MaxCrossSectionSpeedinlet] = ...
             ComputeSpeedAtEvaluationPts(CirclePtsinlet(:,:,1), ...
                                         VelocityInsideDomain(:,rangeInd));

%% Speed computation of outlet cross-section of vessel
numelCirclePtsXoutlet = numel(CirclePtsXoutlet);
numelLinePtsCirclePtsmid_inlet_outlet = numelLinePtsCirclePtsmid_inlet + ...
                                        numelCirclePtsXoutlet;
rangeInd = numelLinePtsCirclePtsmid_inlet+1 : ...
                                     numelLinePtsCirclePtsmid_inlet_outlet;
[CrossSectionSpeedoutlet, ...
 MinCrossSectionSpeedoutlet, MaxCrossSectionSpeedoutlet] = ...
             ComputeSpeedAtEvaluationPts(CirclePtsoutlet(:,:,1), ...
                                         VelocityInsideDomain(:,rangeInd));

%%
MinCaxis = min([MinLineSpeed MinCrossSectionSpeedmid ...
                             MinCrossSectionSpeedinlet ...
                             MinCrossSectionSpeedoutlet]);
MaxCaxis = max([MaxLineSpeed MaxCrossSectionSpeedmid ...
                             MaxCrossSectionSpeedinlet ...
                             MaxCrossSectionSpeedoutlet]);