function Plot_VectorFields(coord, connect, ...
                           coordx, coordy, coordz, ...
                           Fieldx, Fieldy, Fieldz, ...
                           Scaleind, LineWidthind, MaxHeadSizeind)

figure('Color','white')
hold on
Plot_Mesh(coord, connect, 0.25, false, false)
quiver3(coordx, coordy, coordz, ...
        Fieldx, Fieldy, Fieldz, ...
        Scaleind, 'k', 'LineWidth', LineWidthind, ...
        'MaxHeadSize',MaxHeadSizeind),
axis off
axis equal
box off
