function Plot_TractionPressureShearFieldsOnVessel...
            (coord, connect, wallnodeOnlyWallLine, ...
             coordPatchx, coordPatchy, coordPatchz, ...
             TubeRadius, TubeLength, ...
             Telem, InletPressure, NormalVNodal, NormalVNodalPatch, ...
             connectIndArrange, connectArrangedInd, ...
             numElem, numDofPerNode, numDofPerElem, numNodesPerElem, ...
             Scaleind, MarkerSizeind, LineWidthind, ...
             MaxHeadSizeind, TransparencyInd, ...
             verbose_PrintProfiles, PlotVectorFieldsIsTrue)

%% Nodal traction, pressure and shear fields
[TractionNodalPatch, ...
 NormTractionNodalPatch, NormTractionNodalArranged, ...
 MinNormTractionNodalPatch, MaxNormTractionNodalPatch, ...
 PressureNodalPatch, ...
 NormPressureNodalPatch, NormPressureNodalArranged, ...
 MinNormPressureNodalPatch, MaxNormPressureNodalPatch, ...
 ShearNodalPatch, ...
 NormShearNodalPatch, NormShearNodalArranged, ...
 MinNormShearNodalPatch, MaxNormShearNodalPatch] = ...
 TractionPressureShearFields_Nodal_Patch(Telem, ...
                                         NormalVNodal, ...
                                         NormalVNodalPatch, ...
                                         connectIndArrange, ...
                                         connectArrangedInd, ...
                                         numElem, ...
                                         numDofPerNode, ...
                                         numDofPerElem, ...
                                         numNodesPerElem);

%% Patch graph for norm of tractions
Plot_PatchColorFields(coord, connect, wallnodeOnlyWallLine, ...
                      coordPatchx, coordPatchy, coordPatchz, ...
                      NormTractionNodalPatch, ...
                      MinNormTractionNodalPatch, ...
                      MaxNormTractionNodalPatch, ...
                      MarkerSizeind, TransparencyInd)
fig = gcf;
fig.NumberTitle = 'off';
fig.Name = 'NormTractionProfile';
if verbose_PrintProfiles
    print('NormTractionProfile','-dpng','-r0')
end

%% Line graph for norm of tractions
Plot_LineFieldsOnVessel(coord, NormTractionNodalArranged, ...
                               wallnodeOnlyWallLine, ...
                               MarkerSizeind, LineWidthind, ...
                               'Norm of traction, Pa', ...
                               'A line along the vessel wall ($\mu$m)')
fig = gcf;
fig.NumberTitle = 'off';
fig.Name = 'NormTractionLine';
if verbose_PrintProfiles
    print('NormTractionLine','-dpng','-r0')
end

%% Patch graph for norm of pressure
Plot_PatchColorFields(coord, connect, wallnodeOnlyWallLine, ...
                      coordPatchx, coordPatchy, coordPatchz, ...
                      NormPressureNodalPatch, ...
                      MinNormPressureNodalPatch, ...
                      MaxNormPressureNodalPatch, ...
                      MarkerSizeind, TransparencyInd)
fig = gcf;
fig.NumberTitle = 'off';
fig.Name = 'NormPressureProfile';
if verbose_PrintProfiles
    print('NormPressureProfile','-dpng','-r0')
end

%% Line graph for norm of pressure
Plot_LineFieldsOnVessel(coord, NormPressureNodalArranged, ...
                               wallnodeOnlyWallLine, ...
                               MarkerSizeind, LineWidthind, ...
                               'Pressure, Pa', ...
                               'A line along the vessel wall ($\mu$m)')
fig = gcf;
fig.NumberTitle = 'off';
fig.Name = 'NormPresureLine';
if verbose_PrintProfiles
    print('NormPresureLine','-dpng','-r0')
end

%% Patch graph for norm of shear
Plot_PatchColorFields(coord, connect, wallnodeOnlyWallLine, ...
                      coordPatchx, coordPatchy, coordPatchz, ...
                      NormShearNodalPatch, ...
                      MinNormShearNodalPatch, ...
                      MaxNormShearNodalPatch, ...
                      MarkerSizeind, TransparencyInd)
fig = gcf;
fig.NumberTitle = 'off';
fig.Name = 'NormShearProfile';
if verbose_PrintProfiles
    print('NormShearProfile','-dpng','-r0')
end

%% Line graph for norm of shear
Plot_LineFieldsOnVessel(coord, NormShearNodalArranged, ...
                               wallnodeOnlyWallLine, ...
                               MarkerSizeind, LineWidthind, ...
                               'Norm of shear, Pa', ...
                               'A line along the vessel wall ($\mu$m)')
ConstantShearOnVesselSideWall = NormShearNodalArranged(wallnodeOnlyWallLine);
AnalyticalConstantShearOnVesselSideWall = ...
              InletPressure*(pi*TubeRadius^2)/(2*pi*TubeRadius*TubeLength)
fig = gcf;
fig.NumberTitle = 'off';
fig.Name = 'NormShearLine';
if verbose_PrintProfiles
    print('NormShearLine','-dpng','-r0')
end

if PlotVectorFieldsIsTrue
    %% Depict TractionNodalPatch
    Plot_VectorFields(coord, connect, ...
                      coordPatchx, coordPatchy, coordPatchz, ...
                      TractionNodalPatch(:,:,1), ...
                      TractionNodalPatch(:,:,2), ...
                      TractionNodalPatch(:,:,3), ...
                      Scaleind, LineWidthind, MaxHeadSizeind)

    %% Depict PressureNodalPatch
    Plot_VectorFields(coord, connect, ...
                      coordPatchx, coordPatchy, coordPatchz, ...
                      PressureNodalPatch(:,:,1), ...
                      PressureNodalPatch(:,:,2), ...
                      PressureNodalPatch(:,:,3), ...
                      Scaleind, LineWidthind, MaxHeadSizeind)

    %% Depicting ShearNodalPatch
    Plot_VectorFields(coord, connect, ...
                      coordPatchx, coordPatchy, coordPatchz, ...
                      ShearNodalPatch(:,:,1), ...
                      ShearNodalPatch(:,:,2), ...
                      ShearNodalPatch(:,:,3), ...
                      Scaleind, LineWidthind, MaxHeadSizeind)
end