function [TractionNodalPatch, ...
          NormTractionNodalPatch, NormTractionNodalArranged, ...
          MinNormTractionNodalPatch, MaxNormTractionNodalPatch, ...
          PressureNodalPatch, ...
          NormPressureNodalPatch, NormPressureNodalArranged, ...
          MinNormPressureNodalPatch, MaxNormPressureNodalPatch, ...
          ShearNodalPatch, ...
          NormShearNodalPatch, NormShearNodalArranged, ...
          MinNormShearNodalPatch, MaxNormShearNodalPatch] = ...
          TractionPressureShearFields_Nodal_Patch(Telem, ...
                                                  NormalVNodal, ...
                                                  NormalVNodalPatch, ...
                                                  connectIndArrange, ...
                                                  connectArrangedInd, ...
                                                  numElem, ...
                                                  numDofPerNode, ...
                                                  numDofPerElem, ...
                                                  numNodesPerElem)
%% Nodal traction field
TractionNodalx = Telem(1:numDofPerNode:numDofPerElem,:);
TractionNodaly = Telem(2:numDofPerNode:numDofPerElem,:);
TractionNodalz = Telem(3:numDofPerNode:numDofPerElem,:);
TractionNodal = zeros(numNodesPerElem,numElem,numDofPerNode);
TractionNodal(:,:,1) = TractionNodalx;
TractionNodal(:,:,2) = TractionNodaly;
TractionNodal(:,:,3) = TractionNodalz;
NormTractionNodal = sqrt(TractionNodal(:,:,1).^2 + ...
                         TractionNodal(:,:,2).^2 + ...
                         TractionNodal(:,:,3).^2);
NormTractionNodalArranged = NormTractionNodal(connectArrangedInd);

TractionNodalPatchx = TractionNodalx(connectIndArrange,:);
TractionNodalPatchy = TractionNodaly(connectIndArrange,:);
TractionNodalPatchz = TractionNodalz(connectIndArrange,:);
TractionNodalPatch = zeros(length(connectIndArrange),numElem,numDofPerNode);
TractionNodalPatch(:,:,1) = TractionNodalPatchx;
TractionNodalPatch(:,:,2) = TractionNodalPatchy;
TractionNodalPatch(:,:,3) = TractionNodalPatchz;
NormTractionNodalPatch = sqrt(TractionNodalPatch(:,:,1).^2 + ...
                              TractionNodalPatch(:,:,2).^2 + ...
                              TractionNodalPatch(:,:,3).^2);
MaxNormTractionNodalPatch = max(NormTractionNodalPatch(:));
MinNormTractionNodalPatch = min(NormTractionNodalPatch(:));

%% Nodal pressure field
PressureNodal = NormalVNodal.* sum(TractionNodal.*NormalVNodal,3);
NormPressureNodal = sqrt(PressureNodal(:,:,1).^2 + ...
                         PressureNodal(:,:,2).^2 + ...
                         PressureNodal(:,:,3).^2);
NormPressureNodalArranged = NormPressureNodal(connectArrangedInd);

PressureNodalPatch = NormalVNodalPatch.* ...
                     sum(TractionNodalPatch.*NormalVNodalPatch,3);
NormPressureNodalPatch = sqrt(PressureNodalPatch(:,:,1).^2 + ...
                              PressureNodalPatch(:,:,2).^2 + ...
                              PressureNodalPatch(:,:,3).^2);
MaxNormPressureNodalPatch = max(NormPressureNodalPatch(:));
MinNormPressureNodalPatch = min(NormPressureNodalPatch(:));

%% Nodal shear field
ShearNodal = TractionNodal - PressureNodal;
NormShearNodal = sqrt(ShearNodal(:,:,1).^2 + ...
                      ShearNodal(:,:,2).^2 + ...
                      ShearNodal(:,:,3).^2);
NormShearNodalArranged = NormShearNodal(connectArrangedInd);

ShearNodalPatch = TractionNodalPatch - PressureNodalPatch;
NormShearNodalPatch = sqrt(ShearNodalPatch(:,:,1).^2 + ...
                           ShearNodalPatch(:,:,2).^2 + ...
                           ShearNodalPatch(:,:,3).^2);
MaxNormShearNodalPatch = max(NormShearNodalPatch(:));
MinNormShearNodalPatch = min(NormShearNodalPatch(:));
