function KxN = WeaklySingular_ElementIntegrals_KxN(chi, xi_e, ...
                                                   xnodenum, ...
                                                   grx, grw, gtx, gtw)
%%
% chi           coordinates of target point
% xi_e          matrix of element node coord (3x9)
% xnodenum      node number of target point in element
% grx, grw      gauss node coordinates and weights for radial direction r
% gtx, gtw      gauss node coordinates and weights for polar angle theta 
% KxN           weakly-singular element integral
%%
switch xnodenum
    case 1
        zetachi1 = -1; 
        zetachi2 = -1;
        % Triangle 1
        thet_min = 0; 
        thet_max = pi/4; 
        rmax_fn = 1;
        KxN_tr1 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 2
        thet_min = pi/4; 
        thet_max = pi/2; 
        rmax_fn = 2;
        KxN_tr2 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        KxN = KxN_tr1 + KxN_tr2;
    case 2
        zetachi1 = 1; 
        zetachi2 = -1;
        % Triangle 1
        thet_min = pi/2; 
        thet_max = 3*pi/4; 
        rmax_fn = 3;
        KxN_tr1 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 2
        thet_min = 3*pi/4; 
        thet_max = pi; 
        rmax_fn = 4;
        KxN_tr2 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        KxN = KxN_tr1 + KxN_tr2;
    case 3
        zetachi1 = 1; 
        zetachi2 = 1;
        % Triangle 1
        thet_min = pi; 
        thet_max = 5*pi/4; 
        rmax_fn = 5;
        KxN_tr1 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 2
        thet_min = 5*pi/4; 
        thet_max = 3*pi/2; 
        rmax_fn = 6;
        KxN_tr2 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        KxN = KxN_tr1 + KxN_tr2;
    case 4
        zetachi1 = -1; 
        zetachi2 = 1;
        % Triangle 1
        thet_min = 3*pi/2; 
        thet_max = 7*pi/4; 
        rmax_fn = 7;
        KxN_tr1 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 2
        thet_min = 7*pi/4; 
        thet_max = 2*pi; 
        rmax_fn = 8;
        KxN_tr2 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        KxN = KxN_tr1 + KxN_tr2;
    case 5
        zetachi1 = 0; 
        zetachi2 = -1;
        % Triangle 1
        thet_min = 0; 
        thet_max = atan2(2,1); 
        rmax_fn = 9;
        KxN_tr1 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 2
        thet_min = atan2(2,1); 
        thet_max = atan2(2,-1); 
        rmax_fn = 10;
        KxN_tr2 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 3
        thet_min = atan2(2,-1); 
        thet_max = pi; 
        rmax_fn = 11;
        KxN_tr3 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        KxN = KxN_tr1 + KxN_tr2 + KxN_tr3;
    case 6
        zetachi1 = 1; 
        zetachi2 = 0;
        % Triangle 1
        thet_min = pi/2; 
        thet_max = atan2(1,-2); 
        rmax_fn = 12;
        KxN_tr1 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 2
        thet_min = atan2(1,-2); 
        thet_max = atan2(-1,-2) + 2*pi;
        rmax_fn = 13;
        KxN_tr2 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 3
        thet_min = atan2(-1,-2) + 2*pi; 
        thet_max = 3*pi/2;
        rmax_fn = 14;
        KxN_tr3 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        KxN = KxN_tr1 + KxN_tr2 + KxN_tr3;
    case 7
        zetachi1 = 0; 
        zetachi2 = 1;
        % Triangle 1
        thet_min = pi; 
        thet_max = atan2(-2,-1) + 2*pi; 
        rmax_fn = 15;
        KxN_tr1 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 2
        thet_min = atan2(-2,-1) + 2*pi; 
        thet_max = atan2(-2,1) + 2*pi;
        rmax_fn = 16;
        KxN_tr2 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 3
        thet_min = atan2(-2,1) + 2*pi; 
        thet_max = 2*pi;
        rmax_fn = 17;
        KxN_tr3 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        KxN = KxN_tr1 + KxN_tr2 + KxN_tr3;
    case 8
        zetachi1 = -1; 
        zetachi2 = 0;
        % Triangle 1
        thet_min = -pi/2; 
        thet_max = atan2(-1,2); 
        rmax_fn = 18;
        KxN_tr1 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 2
        thet_min = atan2(-1,2); 
        thet_max = atan2(1,2);
        rmax_fn = 19;
        KxN_tr2 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 3
        thet_min = atan2(1,2); 
        thet_max = pi/2;
        rmax_fn = 20;
        KxN_tr3 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        KxN = KxN_tr1 + KxN_tr2 + KxN_tr3;
    case 9
        zetachi1 = 0; 
        zetachi2 = 0;
        % Triangle 1
        thet_min = -pi/4; 
        thet_max = pi/4; 
        rmax_fn = 21;
        KxN_tr1 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 2
        thet_min = pi/4; 
        thet_max = 3*pi/4;
        rmax_fn = 22;
        KxN_tr2 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 3
        thet_min = 3*pi/4; 
        thet_max = 5*pi/4;
        rmax_fn = 23;
        KxN_tr3 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        % Triangle 4
        thet_min = 5*pi/4; 
        thet_max = 7*pi/4;
        rmax_fn = 24;
        KxN_tr4 = WeaklySingularIntegrals_KxN(xi_e, chi, ...
                                              zetachi1, zetachi2, ...
                                              thet_min, thet_max, ...
                                              rmax_fn,...
                                              grx, grw, gtx, gtw);
        KxN = KxN_tr1 + KxN_tr2 + KxN_tr3 + KxN_tr4;
end
